---
output: 
html_document:
  number_sections=TRUE
pagetitle: Assignment_7
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Assignment 7**

In this assignment, you will use R (within R-Studio) to:

+ Take a real life data set and wrangle it into shape
+ Make some exploratory analyses on that cleaned data

**All file paths should be relative, starting from *your* Assignment_7 directory!!**

**This means that you need to create a new R-Project named "Assignment_7.Rproj" in your Assignment_7 directory, and work from scripts within that.**


## **For credit...**

1.  Push a completed version of your Rproj and R-script (details at end of this assignment) to GitHub
2.  Your score will also depend on whether any files generated in this workflow are found in your repository


____________

# Your tasks:

  + Import the `Assignment_7/Utah_Religions_by_County.csv` data set
  + Clean it up into "tidy" shape
  + Explore the cleaned data set with a series of figures (I want to see you exploring the data set)
  + Address the questions: 
    
    1. "Does population of a county correlate with the proportion of any specific religious group in that county?"
    2. "Does proportion of any specific religion in a given county correlate with the proportion of non-religious people?"
    
  + Just stick to figures and maybe correlation indices...no need for statistical tests yet
  
  + Add comment lines that show your thought processes
_____________


