---
title: "Assignment 3"
pagetitle: "Microbiome Bootcamp - Ass. 3"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE,message = FALSE)
```

## Task 1: Find some external metadata

We don't have much metadata about our samples to work with. Really, we just have GPS coordinates. But, GPS coordinates allow us a lot of opportunities to derive secondary metadata. For example, we can pull mean annual temperature for each location. We could also see seafloor depth, and maybe even find biodiversity metrics for these locations.

**Find external sources to derive secondary metadata.** Maybe you have to go to scientific papers. Maybe the data you want isn't there in a clean format, but you could pull together a couple sources to create it. Be creative! Maybe you want to look at plastic pollution levels. Well good luck finding that data set... but there are data about country-level plastic-to-ocean pollution at [https://ourworldindata.org/plastic-pollution](https://ourworldindata.org/plastic-pollution) and combining that in a clever way with ocean current data (link below), could give you a fun proxy for how much plastic pollution you'd expect at a given location. Just an example of how you might need to break apart a question into multiple data sources and combine them.

Just a few starting suggestions.

  - [NOAA](https://www.noaa.gov/)
  - [NASA](https://data.nasa.gov/)
  - [NCEI](https://www.ncei.noaa.gov/products/world-ocean-database)
  - [Seagrass data](https://data.noaa.gov/dataset/dataset/seagrasses)
  - [Ocean currents](https://www.ncei.noaa.gov/products/global-ocean-currents-database)
  
___

## Task 2: Pull the data into tidy format and merge with our metadata

  - Best to do this with a local copy of the metadata until you get it looking really tidy.
  - But whatever you do to wrangle that data, do it with code and document all downloading instructions, versions, and steps.
  - Keep track of citation info as well, and add appropriate citations to our library with a note in them
  
___

## Task 3: Share what you did with the class

<br>
<br>


