---
title: "Assignment 5"
pagetitle: "Microbiome Bootcamp - Ass. 5"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE,message = FALSE)
```

## Task 1: Find some external metadata

We don't have much metadata about our samples to work with. Really, we just have GPS coordinates. But, GPS coordinates allow us a lot of opportunities to derive secondary metadata. For example, we can pull elevation for each location. 

**Find external sources to derive secondary metadata.** Maybe you have to go to scientific papers. Maybe the data you want aren't there in a clean format, but you could pull together a couple sources to create it. Be creative! 
  
___

## Task 2: Pull the data into tidy format and merge with our metadata

  - Best to do this with a local copy of the metadata until you get it looking really tidy.
  - But whatever you do to wrangle that data, do it with code and document all downloading instructions, versions, and steps.
  - Keep track of citation info as well, and add appropriate citations to our library with a note in them
  
___

## Task 3: Share what you did with the class

<br>
<br>


