---
output: 
html_document:
  number_sections=TRUE
pagetitle: Assignment_6
---
    
# **Bioinformatics Data Skills**
    
## Assignment 6

___

  **1. Read through Chapter 7 at least twice**
    
  **2. It's a big chapter which is why we've got 2 weeks with it, but pay attention to things like grep, sed, awk, etc... **
    
  **3. Here's a [fasta file](https://gzahn.github.io/binf-data-skills/Data/Assignment_6_File_1.fasta.gz) (Assignment_6_File_1.fasta.gz) you should download into an appropriate place in your Assignment_6 project directory and uncompress it.**
        
  **4.  I need you to convert that file into tabular format using some combination of the tools you've learned. Tabular format looks like the following:**
  
    OTU8      TACGGAGGGTGCAAGC...
    OTU11     TGGCAGACTAGAGTAT...
 
  The first column is *just* the OTUID, the second column is *just* the sequence; one line per sequence          
  
  **5.  Keep track of any steps you take to convert from fasta to that tabular (with two columns) format, and save the new version of the data file as "Assignment_6_File_1.tsv**
  
  **6.  Now, starting from that new tabular file, use paste/awk/sed/etc. to convert it back to standard fasta format. Record all your commands that got the job done.**
  
  **7.  Okay, now download this other [fasta file](https://gzahn.github.io/binf-data-skills/Data/Assignment_6_File_2.fasta.gz) (Assignment_6_File_2.fasta.gz) ... get it uncompressed. This file is essentially the same as the first file, but the fasta headers contain taxonomic assignments for each sequence in the format: Kingdom;Phylum;Class;Order;Family;Genus**
    
  **8.  Write a short pipeline to extract an alphabetical list of the unique genera that were identified in the Enterobacteriaceae family**
  
  **9.  Create a tab-separated list consisting of 2 columns:**
      
  Column 1 = full taxonomy of all genera found in the Enterobacteriaceae family
      
  Column 2 = the number of times that genus was observed in this file
    
    Example output:  
        >Bacteria;Proteobacteria;Gammaproteobacteria;Enterobacteriales;Enterobacteriaceae;Proteus;	5
        >Bacteria;Proteobacteria;Gammaproteobacteria;Enterobacteriales;Enterobacteriaceae;Tatumella;	6
        >Bacteria;Proteobacteria;Gammaproteobacteria;Enterobacteriales;Enterobacteriaceae;Buttiauxella;	7
        >Bacteria;Proteobacteria;Gammaproteobacteria;Enterobacteriales;Enterobacteriaceae;Escherichia/Shigella;	7

  
  **10.  Export that list to a new file named "Enterobacteriaceae_Genus_Counts.tsv"**

___
  
### **What to turn in:**

  - Store a cleaned-up plain-text file that documents the code you used for tasks 3-10
  - Be sure to include comments explaining what is going on in your code
  
Upload that plain-text file to Canvas. You'll be graded on completeness, documentation, and readability.

___

<br/>