---
output: 
html_document:
  number_sections=TRUE
pagetitle: Assignment_2
---

# **Bioinformatics Data Skills**

## Assignment 2

___

**1. Read through Chapter 2 at least once (you can skip the final section of rendering Markdown to HTML)**

**2. Work through Chapter 2, typing all the code examples from the text into your own terminal. (Any example data used in the chapters can be found in the supplemental repository online)**

  + Every line in the book in 'courier new' font that begins with '$' denotes a line of code that you can try on your own computer!
  
For example (don't type the '$'):

    $ mkdir zmays-snps

**3. Decide on a project structure that works for you (this can change in the future as you gain more experience) and create a blank project template in a single directory on your computer using code.**

**4. Upload (to Canvas) a plain-text document with each line of code, in order, used to create your blank project.**


At a minimum, your project directory template should have a README file and subdirectories for:
  
  - data
  - scripts
  - output
