---
output: html_document
---

<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

## [HOME](http://gzahn.github.io/) | [ABOUT ME](http://gzahn.github.io/about-me/) | [LAB](http://gzahn.github.io/lab/) | [RESEARCH](http://gzahn.github.io/pubs-and-pres/) | [BLOG](http://gzahn.github.io/blog-archive/)

<style>
div.gray { background-color:#aabdaf; border-radius: 5px; padding: 20px;}
</style>
<div class = "gray">

# Publications

[Google Scholar Profile](https://scholar.google.com/citations?user=CkjjlnwAAAAJ&hl=en&oi=ao)

___

**Benjamin J. Wainwright, Geoffrey L. Zahn, Joshua Zushi, Nicole Li Ying Lee, Jillian Lean Sim Ooi, Jen Nie Lee, Danwei Huang. 2019. Seagrass-associated fungal communities show distance decay of similarity that has implications for seagrass management and restoration. Ecology and Evolution. https://doi.org/10.1002/ece3.5631**

Even with few presumed barriers to dispersal, seagrass-associated fungal communities appear to be structured by location.

___

**Wainwright, B. J., Bauman, A. G., Zahn, G. L., Todd, P. A., & Huang, D. 2019. Characterization of fungal biodiversity and communities associated with the reef macroalga Sargassum ilicifolium reveals fungal community differentiation according to geographic locality and algal structure. Marine Biodiversity. https://doi.org/10.1007/s12526-019-00992-6**

Fungal community structure varies between macroalga structures, but the majority of fungi amplified were not classifiable. This highlights the need to better explore and catalog the diversity of marine fungi.

___

**BJ Wainwright, L Afiq-Rosli, GL Zahn, D Huang. 2019. Characterisation of coral-associated bacterial communities in an urbanised marine environment shows strong divergence over small geographic scales. Coral Reefs, 1-10. https://doi.org/10.1007/s00338-019-01837-1**

Even in a geographically small area (Singapore), coral bacteria were different on windward and leeward sides of islands. This may need to be kept in mind when designing coral recovery strategies.i

___

**G Zahn, AS Amend. 2019. Foliar fungi alter reproductive timing and allocation in Arabidopsis under normal and water-stressed conditions. Fungal Ecology 41, 101-106. https://doi.org/10.1016/j.funeco.2019.04.002**

What we think of as “plant” traits, may actually be microbial traits in disguise. Here, fungal endophytes, regardless of identity, increased flowering time and seed mass in Arabidopsis thalliana.

___

**Wainwright BJ., Zahn GL., Arlyza IS., Amend AS. 2018. Seagrass-associated fungal communities follow Wallace’s line, but host genotype does not structure fungal community. Journal of Biogeography:n/a-n/a. DOI: 10.1111/jbi.13168.**

Fungi associated with the seagrass Syringodium isoetifolium had different community structure on either side of Wallace’s Line, a theoretical boundary that separates Asian and Australasian flora and fauna. This suggests that whatever processes enforce this “boundary” in macro organisms may be at work at the microbial scale as well.

___

**Zahn G., Amend AS. 2017. Foliar microbiome transplants confer disease resistance in a critically-endangered plant. PeerJ 5:e4020. DOI: 10.7717/peerj.4020. https://peerj.com/articles/4020/**

A conservation story with a happy ending: A simple, low-tech method of transplanting endophytic fungi from healthy relatives strongly reduced disease mortality and increased out-planting success of the endangered endemic Hawaiian mint, Phyllostegia kaalaensis. Plant conservation efforts can be greatly improved by considering plant microbiomes. Read more here: https://www.sciencenews.org/article/plant-microbes-crops-food-endangered-species

___

**Datlof EM, Amend AS, Earl K, Hayward J, Morden CW, Wade R, Zahn G, Hynson NA. (2017) Uncovering unseen fungal diversity from plant DNA banks. PeerJ 5:e3730 https://doi.org/10.7717/peerj.3730**

DNA banks house a wealth of genetic information, even for endangered and extinct plants. But they also hold information about the microbes present when the DNA was collected. They can be harnessed to ask historical questions about plant-microbe symbioses.

___

**Wainwright BJ, Zahn GL, Spalding HL, Sherwood AR, Smith CM, Amend AS. (2017) Fungi associated with mesophotic macroalgae from the ‘Au‘au Channel, west Maui are differentiated by host and overlap terrestrial communities. PeerJ 5:e3532 https://doi.org/10.7717/peerj.3532**

Even 100m below the surface of the ocean, in the mesophotic zone, fungi are associating with algae. Roughly a third of the fungi recovered were also found in nearby terrestrial plants, showing the potential for wide host ranges. This unexplored ecosystem should be considered when estimating global fungal biodiversity.

___

**Geoffrey Zahn, Rota Wagai, Seiichiro Yonemura. 2016. The effects of amoebal bacterivory on carbon and nitrogen dynamics depend on temperature and soil structure interactions. Soil Biology and Biochemistry, 94:133-137. DOI 10.1016/j.soilbio.2015.11.021**

Amoebae in soils are some of the top bacterial predators, and they are responsible for helping determine C and N turnover rates. But with global warming and changes to agricultural management practices, the effect of amoebal bacterivory is altered. Soil carbon models (Q10) should incorporate food web dynamics to increase accuracy.

___

**Geoffrey Zahn, Steven L. Stephenson, Frederick W. Spiegel. 2014. Ecological distribution of protosteloid amoebae in New Zealand. PeerJ 2:e296; DOI 10.7717/peerj.296**

In a thorough survey of New Zealand, we detected broad environmental influences on the distribution of 30 protosteloid amoebae. Latitude, precipitation, and elevation matter as limiters of distribution.

___

**Miriam De Haan, Christine Cocquyt, Alex Tice, Geoffrey Zahn, Frederick W. Spiegel. 2014. First records of Protosteloid Amoebae (Eumycetozoa) from the Democratic Republic of the Congo. Plant Ecology and Evolution, 147:1, 85-92; https://doi.org/10.5091/plecevo.2014.883**

The high species diversity observed on a limited number of samples suggests that the DRC region is, together with Hawai’i, one of the world’s tropical hotspots for protosteloid amoeba diversity.

___

**Erin R. Murphy, Jacob Boxberger, Robert Colvin, Suk Je Lee, Geoffrey Zahn, Fred Loor, Kyoungtae Kim. 2011. Pil1, an eisosome organizer, plays an important role in the recruitment of synaptojanins and amphiphysins to facilitate receptor-mediated endocytosis in yeast. European Journal of Cell Biology, 90:10, 825-833. https://doi.org/10.1016/j.ejcb.2011.06.006**

The title says it all.

</div>

___

<style>
div.blue { background-color:#a89d82; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">

# COMING SOON ...
Fungi in the atmosphere: A decade of air samples from Mauna Loa Observatory<br>
Extremophile fungi in The Great Salt Lake<br>
Fungal community recovery after forest fires<br>
Human oral mycobiome determinants<br>
More coral microbiomes!<br>
Including outgroups in fungal meta-barcoding studies<br>


</div>


_____




